---
title: "Curso - SEM, CFA, EFA, IRT, Mediation/Moderation, Mixed model, Network"
author: "Mauricio Scopel Hoffmann"
date: "18 AGO 2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Settings
```{r settings 1, message=F, warning=F, echo=F}
# packages
library(rio); library(dplyr); library(tidyverse); library(car); library(sjlabelled); library(sjPlot); library(performance); library(lme4); library(ggeffects); library(table1); library(psych); library(ggcorrplot); library(polycor); library(EGAnet); library(qgraph); library(glasso); library(igraph); library(bootnet); library(psychonetrics); library(mlVAR); library(lavaan); library(semPlot); library(ltm); library(mirt); library(ggpubr); library(ggridges); library(rstatix); library(hrbrthemes); library(knitr)

# set WD
setwd("~/Dropbox/Maurício Hoffmann/UFSM/PPG Psiquiatria UFRGS/PSQ92/British Cohorts data set/Data")

# Data sets for NCDS
data_ncds_demographics <- import("ncds_keyvariables.sav")

data_ncds_rutter <- import("n016rutter.sav") %>% dplyr::select(-n0sex, -n0region, -n0bwght, -n0bwght1, -n0rgsc, -n0mumed, -n7rgsc, -n7crowd, -n7crowdg, -n7ownh, -n11rgsc, -n11fsm, -n11bens, -n11mint, -n11fint, -n11read, -n11maths, -n16rgsc, -n16mrgsc, -n16ledu, -n16finhd, -n23rgsc, -n33rgsc, -n42rgsc, -n42lefted, -n42hq8, -n42hq6)

data_ncds_malaise <- import("n042malaise.sav")%>% dplyr::select(-n0sex, -n0region, -n0bwght, -n0bwght1, -n0rgsc, -n0mumed, -n7rgsc, -n7crowd, -n7crowdg, -n7ownh, -n11rgsc, -n11fsm, -n11bens, -n11mint, -n11fint, -n11read, -n11maths, -n16rgsc, -n16mrgsc, -n16ledu, -n16finhd, -n23rgsc, -n33rgsc, -n42rgsc, -n42lefted, -n42hq8, -n42hq6)

data_ncds_math <- import("n716maths.sav") %>% dplyr::select(-n0sex, -x, -n11math) 

data_ncds_reading <- import("n716reading.sav") %>% dplyr::select(-n0sex, -x, -n7age, -n11age, -n16age, -n11read)

# Combining data sets into one
mydata <- left_join(data_ncds_demographics, data_ncds_rutter, by="ncdsid")
mydata <- left_join(mydata, data_ncds_malaise, by="ncdsid")
mydata <- left_join(mydata, data_ncds_math, by="ncdsid")
mydata <- left_join(mydata, data_ncds_reading, by="ncdsid")

names(mydata) # get variable names
get_label(mydata$n0region) # get a specific variable label/question
get_labels(mydata$n0region) # get response options from a specific variable
summary.factor(mydata$n0region)
class(mydata$n0region) 
glimpse(mydata) 
hist(mydata$n0bwght) 

# Recode variable names
#mydata<-dplyr::rename(mydata,`UK region`=n0region)

mydata <- mydata %>% 
  rename(A_Rutter_total_7 = n7mrutt) %>%
  rename(A_Rutter_total_11 = n11mrutt) %>%
  rename(A_Rutter_total_16 = n16mrutt) %>%
  rename(B_Rutter_total_16 = n16rutt) %>%
  rename(A_Unsettle_7 = n7rut01) %>%
  rename(A_Solitary_7 = n7rut02) %>%
  rename(A_Bullied_7 = n7rut03) %>% # not used in total score
  rename(A_Destroys_7 = n7rut04) %>% # not used in total score
  rename(A_Miserable_7 = n7rut05) %>%
  rename(A_Fidgety_7 = n7rut06) %>%
  rename(A_Worries_7 = n7rut07) %>%
  rename(A_Irritable_7 = n7rut08) %>%
  rename(A_Sucks_thumb_7 = n7rut09) %>%
  rename(A_Upset_7 = n7rut10) %>%
  rename(A_Twitches_7 = n7rut11) %>%
  rename(A_Fights_7 = n7rut12) %>%
  rename(A_Nail_bite_7 = n7rut13) %>%
  rename(A_Disobedient_7 = n7rut14) %>%
  rename(A_Unsettle_11 = n11rut01) %>%
  rename(A_Solitary_11 = n11rut02) %>%
  rename(A_Bullied_11 = n11rut03) %>% # not used in total score
  rename(A_Destroys_11 = n11rut04) %>% # not used in total score
  rename(A_Miserable_11 = n11rut05) %>%
  rename(A_Fidgety_11 = n11rut06) %>%
  rename(A_Worries_11 = n11rut07) %>%
  rename(A_Irritable_11 = n11rut08) %>%
  rename(A_Sucks_thumb_11 = n11rut09) %>%
  rename(A_Upset_11 = n11rut10) %>%
  rename(A_Twitches_11 = n11rut11) %>%
  rename(A_Fights_11 = n11rut12) %>%
  rename(A_Nail_bite_11 = n11rut13) %>%
  rename(A_Disobedient_11 = n11rut14) %>%
  rename(A_Restless_16 = n16rut01) %>%
  rename(A_Fidgety_16 = n16rut02) %>%
  rename(A_Destroys_16 = n16rut03) %>% 
  rename(A_Fights_16 = n16rut04) %>% 
  rename(A_Disliked_16 = n16rut05) %>%
  rename(A_Worries_16 = n16rut06) %>%
  rename(A_Solitary_16 = n16rut07) %>%
  rename(A_Irritable_16 = n16rut08) %>%
  rename(A_Miserable_16 = n16rut09) %>%
  rename(A_Twitches_16 = n16rut10) %>%
  rename(A_Sucks_thumb_16 = n16rut11) %>%
  rename(A_Nail_bite_16 = n16rut12) %>%
  rename(A_Disobedient_16 = n16rut13) %>%
  rename(A_Unsettle_16 = n16rut14) %>%
  rename(A_Fearful_16 = n16rut15) %>%
  rename(A_Fussy_16 = n16rut16) %>%
  rename(A_Lies_16 = n16rut17) %>%
  rename(A_Bullies_16 = n16rut18) %>%
  rename(B_Restless_16 = n16rutt01) %>%
  rename(B_Truants_16 = n16rutt02) %>%
  rename(B_Fidgety_16 = n16rutt03) %>% 
  rename(B_Destroys_16 = n16rutt04) %>% 
  rename(B_Fights_16 = n16rutt05) %>% 
  rename(B_Disliked_16 = n16rutt06) %>%
  rename(B_Worries_16 = n16rutt07) %>%
  rename(B_Solitary_16 = n16rutt08) %>%
  rename(B_Irritable_16 = n16rutt09) %>%
  rename(B_Miserable_16 = n16rutt10) %>%
  rename(B_Twitches_16 = n16rutt11) %>%
  rename(B_Sucks_thumb_16 = n16rutt12) %>%
  rename(B_Nail_bite_16 = n16rutt13) %>%
  rename(B_Absent_school_16 = n16rutt14) %>%
  rename(B_Disobedient_16 = n16rutt15) %>%
  rename(B_Unsettle_16 = n16rutt16) %>%
  rename(B_Fearful_16 = n16rutt17) %>%
  rename(B_Fussy_16 = n16rutt18) %>%
  rename(B_Lies_16 = n16rutt19) %>%
  rename(B_Steal_16 = n16rutt20) %>%
  rename(B_Apathetic_16 = n16rutt21) %>%
  rename(B_Aches_16 = n16rutt22) %>%
  rename(B_Tears_16 = n16rutt23) %>%
  rename(B_Stutter_16 = n16rutt24) %>%
  rename(B_Resent_aggressive_16 = n16rutt25) %>%
  rename(B_Bullies_16 = n16rutt26)

```
# Descriptive tables
```{r Descriptive tables, message=F, warning=F}
library(table1)

mydata_descriptive <- mydata
mydata_descriptive <- mydata_descriptive %>% dplyr::filter(n0sex==1|n0sex==2)

# Relabel
mydata_descriptive$n0sex <- 
  factor(mydata_descriptive$n0sex, 
         levels=c(1,2),
         labels=c("Male", # Reference
                  "Female"))

mydata_descriptive$n0rgsc <- 
  factor(mydata_descriptive$n0rgsc, 
         levels=c(1,2,3,4,5,6),
         labels=c("V", # Reference
                  "IV", "IIIm", "IIInm", "II", "I"))

mydata_descriptive$n0region <- 
  factor(mydata_descriptive$n0region, 
         levels=c(1,2,3,4,5,6,7,8,9,10,11),
         labels=c("North Western",  "Northern" , "East & W.Riding", "North Midlands", "Eastern", "London & S.East", "Southern", "South Western", "Midlands", "Wales", "Scotland"))

# Rename
table1::label(mydata_descriptive$n0sex) <- "Biological sex"
table1::label(mydata_descriptive$n0region) <- "UK region"
table1::label(mydata_descriptive$n0rgsc) <- "Parental social class at birth"
table1::label(mydata_descriptive$zn7read) <- "Reading ability at age 7"
table1::label(mydata_descriptive$zn11read) <- "Reading ability at age 11"
table1::label(mydata_descriptive$zn16read) <- "Reading ability at age 16"
table1::label(mydata_descriptive$zn7math) <- "Math ability at age 7"
table1::label(mydata_descriptive$zn11math) <- "Math ability at age 11"
table1::label(mydata_descriptive$zn16math) <- "Math ability at age 16"


my.render.cont <- function(x) {
    with(stats.apply.rounding(stats.default(x), digits=2), c("",
        "Mean (SD)"=sprintf("%s (&plusmn; %s)", MEAN, SD)))
}


my.render.cat <- function(x) {
    c("", sapply(stats.default(x), function(y) with(y,
        sprintf("%d (%0.0f %%)", FREQ, PCT))))
}

# P-value for table1 t.test and chi^2 comparisons
pvalue <- function(x, ...) {
    # Construct vectors of data y, and groups (strata) g
    y <- unlist(x)
    g <- factor(rep(1:length(x), times=sapply(x, length)))
    if (is.numeric(y)) {
        # For numeric variables, perform a standard 2-sample t-test
        p <- kruskal.test(y ~ g)$p.value
    } else {
        # For categorical variables, perform a chi-squared test of independence
        p <- chisq.test(table(y, g))$p.value
    }
    # Format the p-value, using an HTML entity for the less-than sign.
    # The initial empty string places the output on the line below the variable label.
    c("", sub("<", "&lt;", format.pval(p, digits=3, eps=0.001)))
}

# Desriptive table
table1::table1(~ n0region + A_Rutter_total_7 + A_Rutter_total_11 + A_Rutter_total_16 + B_Rutter_total_16 + zn7read +  zn11read + zn16read + zn7math + zn11math + zn16math | n0sex , data = mydata_descriptive, overall=FALSE, render.continuous=my.render.cont, render.categorical=my.render.cat, extra.col=list(`P-value`=pvalue))
```

# Missing data - inverse probability weight for dealing with attrition
```{r  Missing data - inverse probability weight, message=F, warning=F}
# IPW for Reading at age 16
## Generate new data set and attrition variable
mydata_ipw_read16 <- mydata %>% mutate(Attrition_read16= case_when(n16read!="NA" ~ "Yes", TRUE ~ "No"))
mydata_ipw_read16 <- mydata_ipw_read16 %>% mutate_at(vars("Attrition_read16"),ordered)
summary.factor(mydata_ipw_read16$Attrition_read16)

## Selecting variables
mydata_ipw_read16 <- mydata_ipw_read16 %>% dplyr::select(ncdsid, n0sex:n0mumed, Attrition_read16) 

## Filter to complete data in variable with less complete baseline data
#mydata_ipw_read16 <- mydata_ipw_read16[complete.cases(mydata_ipw_read16[ ,2]),]
mydata_ipw_read16 <- mydata_ipw_read16 %>% drop_na()

## Descriptive
table1::table1(~ as.factor(n0sex) + as.factor(n0region) + n0bwght + as.factor(n0bwght1) + as.factor(n0rgsc) + as.factor(n0mumed) | Attrition_read16, data = mydata_ipw_read16, overall=FALSE, extra.col=list(`P-value`=pvalue))

## Logit regression
fit_ipw_read16 <- glm(Attrition_read16 ~ as.factor(n0sex) + as.factor(n0region) + n0bwght + as.factor(n0bwght1) + as.factor(n0rgsc) + as.factor(n0mumed), family=binomial(link='logit'), data=mydata_ipw_read16); summary(fit_ipw_read16)

## Predicted
pw_read16 <- predict(fit_ipw_read16, type="response")

## Invert prediction
ipw_read16 <- 1/pw_read16

## Add to temporary data set 
mydata_ipw_read16 <- cbind(mydata_ipw_read16,ipw_read16) %>% dplyr::select(ncdsid, ipw_read16, Attrition_read16)

### testing 
mydata_ipw_read16_test<- mydata_ipw_read16 %>% filter(Attrition_read16=="Yes")
sum(mydata_ipw_read16_test$ipw_read16)  #should be = 17079 (complete variables at baseline)

## Add ipw to main dataset
mydata <- left_join(mydata, mydata_ipw_read16, by="ncdsid")
summary(mydata$ipw_read16)
quantile(mydata$ipw_read16, c(.01, .99), na.rm = T) # do not need to trimm
#mydata$ipw_read16 <- pewmethods::trim_weights(mydata$ipw_read16, lower_quantile = 0.01, upper_quantile = 0.99)
```

# Transform wide to long four ages 0 to 16
```{r wide to long, message=F, warning=F}
# preprocessing var names
mydata_0 <- mydata %>% dplyr::select(ncdsid:n0mumed); colnames(mydata_0) <- str_replace(colnames(mydata_0), "n0", ""); names(mydata_0)

mydata_7 <- mydata %>% dplyr::select(ncdsid:n0bwght1, n0mumed, n7rgsc:n7ownh, A_Rutter_total_7, n7mruttg, n7in, A_Unsettle_7:A_Disobedient_7, n7math:n7mathage, n7read:n7readage, -n7in); colnames(mydata_7) <- str_replace(colnames(mydata_7), "n7", ""); colnames(mydata_7) <- str_replace(colnames(mydata_7), "_7", ""); colnames(mydata_7) <- str_replace(colnames(mydata_7), "n0", ""); names(mydata_7)

mydata_11 <- mydata %>% dplyr::select(ncdsid:n0bwght1, n0mumed, n11rgsc:n11maths, A_Rutter_total_11, n11mruttg, n11in, A_Unsettle_11:A_Disobedient_11, n11age:n11mathage, zn11read:n11readage, -n11in) %>% dplyr::rename(n11math=n11maths); colnames(mydata_11) <- str_replace(colnames(mydata_11), "n11", ""); colnames(mydata_11) <- str_replace(colnames(mydata_11), "_11", ""); colnames(mydata_11) <- str_replace(colnames(mydata_11), "n0", "");  names(mydata_11)

mydata_16 <- mydata %>% dplyr::select(ncdsid:n0bwght1, n0mumed, n16rgsc:n16finhd, A_Rutter_total_16, n16mruttg, n16in, A_Restless_16:B_Bullies_16, n16math:n16mathage, n16read:n16readage, -n16in); colnames(mydata_16) <- str_replace(colnames(mydata_16), "n16", ""); colnames(mydata_16) <- str_replace(colnames(mydata_16), "_16", ""); colnames(mydata_16) <- str_replace(colnames(mydata_16), "n0", ""); names(mydata_16)

# Creating wave variable
mydata_0$Wave <- 1
mydata_7$Wave <- 2
mydata_11$Wave <- 3
mydata_16$Wave <- 4

# Binding for long data set
mydata_long <- bind_rows(mydata_0, mydata_7, mydata_11, mydata_16)
mydata_long <- mydata_long %>% arrange(ncdsid); names(mydata_long)

```
# Basic regression models
```{r Basic regression models, message=F, warning=F}
library(sjPlot); library(performance); library(lme4); library(ggeffects)
# Transform birth weight to Kg
mydata$n0bwght_Kg <- mydata$n0bwght/1000

# Linear model 
read_model_1 <- lm(zn16read ~ zn7read, data=mydata, weights = ipw_read16); summary(read_model_1)
# Result table
read_model_results <- tab_model(read_model_1, show.intercept = FALSE, show.ci = 0.95, collapse.ci = FALSE, p.style = "numeric", pred.labels = c("Reading at age 7"), dv.labels = c("Reading ability at age 11 (z-score)")); read_model_results

# Multiple models
read_model_2 <- lm(zn11read ~ zn7read + A_Rutter_total_7, data=mydata); summary(read_model_2) 
read_model_2_results <- tab_model(read_model_2, show.intercept = FALSE, show.ci = 0.95, collapse.ci = FALSE, p.style = "numeric", pred.labels = c("Reading at age 7", "Rutter A score at age 7"),
  dv.labels = c("Reading ability at age 11 (z-score)")); read_model_2_results

read_model_3 <- lm(zn11read ~ zn7read + A_Rutter_total_7 + n0bwght_Kg + n0rgsc + n0sex, data=mydata); summary(read_model_3) 
read_model_3_results <- tab_model(read_model_3, show.intercept = FALSE, show.ci = 0.95, collapse.ci = FALSE, p.style = "numeric", pred.labels = c("Reading at age 7", "Rutter A score at age 7", "Birth weight (g)", "Father social class at birth", "Biologicla sex (Ref: Male)"),
  dv.labels = c("Reading ability at age 11 (z-score)")); read_model_3_results

## mixed model
read_model_4 <- lmerTest::lmer(zn11read ~ zn7read + A_Rutter_total_7 + n0bwght_Kg + n0rgsc + n0sex + (1 | n0region), data=mydata); summary(read_model_4) 
read_model_4_results <- tab_model(read_model_4, show.intercept = FALSE, show.ci = 0.95, collapse.ci = FALSE, p.style = "numeric", pred.labels = c("Reading at age 7", "Rutter A score at age 7", "Birth weight (g)", "Father social class at birth", "Biological sex (Ref: Male)"),
  dv.labels = c("Reading ability at age 11 (z-score)")); read_model_4_results

# Checking performance and model comparison
check_model(read_model_3) # performance

compare_performance(read_model_1, read_model_2, read_model_3, read_model_4, rank = T) #model comparison

# Mixed model - time effect
## selecting data
mydata_long_7_to_16 <- mydata_long %>% dplyr::filter(Wave!=1) %>% dplyr::select(ncdsid, sex,Wave, A_Rutter_total, bwght, rgsc, read) %>% drop_na()
mydata_long_7_to_16$bwght_Kg <- mydata_long_7_to_16$bwght/1000
## model

read_model_5 <- lmerTest::lmer(read ~ Wave*A_Rutter_total + bwght_Kg + rgsc + sex + (Wave|ncdsid), data=mydata_long_7_to_16); summary(read_model_5) 

read_model_5_results <- tab_model(read_model_5, show.intercept = FALSE, show.ci = 0.95, collapse.ci = FALSE, p.style = "numeric", pred.labels = c("Wave", "Rutter A score", "Birth weight (g)", "Father social class at birth", "Biological sex (Ref: Male)"),
  dv.labels = c("Reading ability")); read_model_5_results

# Plot trajectory

## Reading by wave
ggplot(mydata_long_7_to_16, aes(x = Wave, y = read)) +  
    geom_line(aes(group = ncdsid), alpha = 0.1) +
    theme_bw(base_size = 16) +  
    xlab("Wave") +  
    ylab("Reading ability")
## Symtpoms by wave
ggplot(mydata_long_7_to_16, aes(x = Wave, y = A_Rutter_total)) +  
    geom_line(aes(group = ncdsid), alpha = 0.1) +
    theme_bw(base_size = 16) +  
    xlab("Wave") +  
    ylab("Symtpoms (Rutter Total score)")
## reading by symptoms
ggplot(mydata_long_7_to_16, aes(x = A_Rutter_total, y = read)) +  
    geom_line(aes(group = ncdsid), alpha = 0.1) +
    theme_bw(base_size = 16) +  
    xlab("Rutter total score") +  
    ylab("Reading ability") + stat_smooth(method = "lm",
              formula = y ~ x,
              geom = "smooth", col="blue")

```

# Data set for factor analysis
```{r Data set for factor analysis, message=F, warning=F}
# Selecting Rutter variables that are consistent across time
mydata_Rutter_fa <- mydata_long %>% dplyr::select(ncdsid:mruttg, math:Wave, A_Unsettle, A_Solitary, A_Destroys, A_Miserable, A_Fidgety, A_Worries, A_Irritable, A_Sucks_thumb, A_Twitches, A_Fights, A_Nail_bite, A_Disobedient,  B_Unsettle, B_Solitary, B_Destroys, B_Miserable, B_Fidgety, B_Worries, B_Irritable, B_Sucks_thumb, B_Twitches, B_Fights, B_Nail_bite, B_Disobedient) %>% dplyr::filter(Wave!=1)
# Selecting data according to ages
mydata_Rutter_7_fa <- mydata_Rutter_fa %>% dplyr::filter(Wave==2)
mydata_Rutter_11_fa <- mydata_Rutter_fa %>% dplyr::filter(Wave==3)
mydata_Rutter_16_fa <- mydata_Rutter_fa %>% dplyr::filter(Wave==4)

# Data for informant measurement invariance
mydata_Rutter_16_MI_T <- mydata_Rutter_16_fa %>% dplyr::select(ncdsid:mumed, B_Disobedient, B_Fights, B_Destroys, B_Fidgety, B_Unsettle, B_Irritable, B_Miserable, B_Worries, B_Solitary); colnames(mydata_Rutter_16_MI_T) <- str_replace(colnames(mydata_Rutter_16_MI_T), "B_", "")
mydata_Rutter_16_MI_T$Informant <- "Teacher"
names(mydata_Rutter_16_MI_T)

mydata_Rutter_16_MI_P <- mydata_Rutter_16_fa %>% dplyr::select(ncdsid:mumed, A_Disobedient, A_Fights, A_Destroys, A_Fidgety, A_Unsettle, A_Irritable, A_Miserable, A_Worries, A_Solitary); colnames(mydata_Rutter_16_MI_P) <- str_replace(colnames(mydata_Rutter_16_MI_P), "A_", "")
mydata_Rutter_16_MI_P$Informant <- "Parent"
names(mydata_Rutter_16_MI_P)

mydata_Rutter_16_MI <- rbind(mydata_Rutter_16_MI_T, mydata_Rutter_16_MI_P)
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,8]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,9]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,10]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,11]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,12]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,13]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,14]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,15]),]
mydata_Rutter_16_MI <- mydata_Rutter_16_MI[complete.cases(mydata_Rutter_16_MI[ ,16]),]

```

# Factor analysis for the Rutter Scale
## EFA
```{r EFA for the Rutter Scale, message=F, warning=F}

#######
# EFA #
#######
library(psych); library(ggcorrplot); library(polycor)

# Parent-report on internalizing and externalizing symtpoms that are present in all the cohort
# Selecting variables and Transforming to numeric
EFA_data_Rutter_16 <- mydata_Rutter_16_fa %>% dplyr::select(A_Disobedient, A_Fights, A_Destroys, A_Fidgety, A_Unsettle, A_Irritable, A_Miserable, A_Worries, A_Solitary) %>% mutate_all(~as.character(.) %>% as.numeric()) 
EFA_data_Rutter_16 <- EFA_data_Rutter_16[complete.cases(EFA_data_Rutter_16[ ,1]),]
# calculating polychoric matrix
EFA_data_Rutter_16_matrix <- psych::mixedCor(EFA_data_Rutter_16, smooth=TRUE, p=1:9)
EFA_data_Rutter_16_poly <- EFA_data_Rutter_16_matrix$rho
# Plotting polychoric correlation matrix
ggcorrplot(EFA_data_Rutter_16_poly)
# How Factorable is our Dataset?
## Bartlett test - p<0.05
cortest.bartlett(EFA_data_Rutter_16_poly, n=11632)
## Kaiser-Meyer-Olkin factor adequacy - MSA must be closer to 1.0 (0 to 1)
KMO(EFA_data_Rutter_16_poly)
# Exploring the number of factors using scree plot
fa.parallel(EFA_data_Rutter_16_poly, n.obs =11632, fa = "fa", fm="wls")
## EFA based on parallel analysis resutls
EFA_data_Rutter_16_poly_2f <- psych::fa(EFA_data_Rutter_16_poly, nfactors = 1, fm="wls", rotate = "oblimin", np.obs=11632); EFA_data_Rutter_16_poly_2f; fa.diagram(EFA_data_Rutter_16_poly_2f)


# Teacher scale at age 16 
# Selecting variables and Transforming to numeric
EFA_data_Rutter_16T <- mydata_Rutter_16_fa %>% dplyr::select(B_Disobedient, B_Fights, B_Destroys, B_Fidgety, B_Unsettle, B_Irritable, B_Miserable, B_Worries, B_Solitary) %>% mutate_all(~as.character(.) %>% as.numeric()) 
EFA_data_Rutter_16T <- EFA_data_Rutter_16T[complete.cases(EFA_data_Rutter_16T[ ,1]),]
# calculating polychoric matrix
EFA_data_Rutter_16T_matrix <- psych::mixedCor(EFA_data_Rutter_16T, c=NULL,smooth=TRUE, p=1:9)
EFA_data_Rutter_16T_poly <- EFA_data_Rutter_16T_matrix$rho
# Plotting polychoric correlation matrix
ggcorrplot(EFA_data_Rutter_16T_poly)
# How Factorable is our Dataset?
## Bartlett test - p<0.05
cortest.bartlett(EFA_data_Rutter_16T_poly, n=12455)
## Kaiser-Meyer-Olkin factor adequacy - MSA must be closer to 1.0 (0 to 1)
KMO(EFA_data_Rutter_16T_poly)
# Exploring the number of factors using scree plot
fa.parallel(EFA_data_Rutter_16T_poly, n.obs =12455, fa = "fa", fm="wls")
## EFA based on parallel analysis resutls
EFA_data_Rutter_16T_poly_4f <- psych::fa(EFA_data_Rutter_16T_poly, nfactors = 2, fm="wls", rotate = "oblimin", np.obs=12455); EFA_data_Rutter_16T_poly_4f; fa.diagram(EFA_data_Rutter_16T_poly_4f)

# EGA
# Exploring with network
library(EGAnet)
# for EGA network
EGA_data_Rutter_16T <- EFA_data_Rutter_16T

EGA_data_Rutter_16T_out <- EGA(data = EGA_data_Rutter_16T, model = "glasso", plot.EGA = T)
par(mfrow=c(1,1))
plot(EGA_data_Rutter_16T_out, label.cex=2)

# Longitudinal network
library(qgraph); library(glasso); library(igraph); library(bootnet); library(psychonetrics); library(mlVAR)
## data
Net_data_Rutter <- mydata_Rutter_fa %>% dplyr::filter(Wave!=1) %>% dplyr::select(Wave, A_Disobedient, A_Fights, A_Destroys, A_Fidgety, A_Unsettle, A_Irritable, A_Miserable, A_Worries, A_Solitary)
## Longitudinal network
fit_Net_data_Rutter <- mlVAR::mlVAR(Net_data_Rutter, vars = c("A_Disobedient", "A_Fights", "A_Destroys", "A_Fidgety", "A_Unsettle", "A_Irritable", "A_Miserable", "A_Worries", "A_Solitary"), idvar="Wave", contemporaneous = "orthogonal", temporal = "orthogonal", scale = T)
plot(fit_Net_data_Rutter, "temporal", nonsig="hide")  #Fixed effect temporal net
plot(fit_Net_data_Rutter, "contemporaneous", nonsig="hide") #Fixed effect contemporaneous net

```
## CFA
```{r CFA for the Rutter Scale, message=F, warning=F}

#######
# CFA #
#######

library(lavaan); library(semPlot)
## 1 Factor Model of A scale at age 16
Rutter_model_1F <- '
General_1F =~ A_Disobedient +  A_Fights +  A_Destroys +  A_Fidgety +  A_Unsettle +  A_Irritable +  A_Miserable +  A_Worries +  A_Solitary 
'

# Fitting the model
fit_Rutter_1F <- cfa(Rutter_model_1F, data=mydata_Rutter_16_fa, ordered = T, std.lv=T, estimator="WLSMV"); summary(fit_Rutter_1F,fit.measures=T, standardized=T, rsquare=T)
#Reliability
semTools::reliability(fit_Rutter_1F)
##Graph
semPaths(fit_Rutter_1F, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2,) # Technical representation


## Correlated factors 
Rutter_model_2F <- '
Internalizing_Corr =~ A_Miserable +  A_Worries +  A_Solitary 
Externalizing_Corr =~ A_Disobedient +  A_Fights +  A_Destroys +  A_Fidgety +  A_Unsettle +  A_Irritable

A_Fidgety ~~  A_Unsettle

'
# Fitting the model
fit_Rutter_2F <- cfa(Rutter_model_2F, data=mydata_Rutter_16_fa, ordered = T, std.lv = T, estimator="WLSMV"); summary(fit_Rutter_2F,fit.measures=T, standardized=T, rsquare=T)
# Modification indices
Mod_Indices_Rutter_2F <- modindices(fit_Rutter_2F, sort = TRUE, maximum.number = 10); Mod_Indices_Rutter_2F[Mod_Indices_Rutter_2F$op == "~~",]

#Reliability
semTools::reliability(fit_Rutter_2F)
##Graph
semPaths(fit_Rutter_2F, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2,) # Technical representation
semPaths(fit_Rutter_2F, residuals=F, intercepts = F,sizeMan=6,"std",
         posCol=c("skyblue3", "red"),
         #edge.color="skyblue4",
         edge.label.cex=1.2,layout="circle")

## Bifactor
Rutter_model_bif <- '
Internalizing_bif =~ A_Miserable +  A_Worries +  A_Solitary 
Externalizing_bif =~ A_Disobedient +  A_Fights +  A_Destroys +  A_Fidgety +  A_Unsettle +  A_Irritable
General_bif =~ A_Miserable +  A_Worries +  A_Solitary + A_Disobedient +  A_Fights +  A_Destroys +  A_Fidgety +  A_Unsettle +  A_Irritable

#Orthogonal
General_bif ~~0* Internalizing_bif
General_bif ~~0* Externalizing_bif
Internalizing_bif ~~0* Externalizing_bif

'
# Fitting the model
fit_Rutter_bif <- cfa(Rutter_model_bif, data=mydata_Rutter_16_fa, ordered = T, std.lv = T, estimator="WLSMV"); summary(fit_Rutter_bif,fit.measures=T, standardized=T, rsquare=T)

# Modification indices
Mod_Indices_Rutter_bif <- modindices(fit_Rutter_bif, sort = TRUE, maximum.number = 10); Mod_Indices_Rutter_bif[Mod_Indices_Rutter_bif$op == "~~",]
#Reliability
semTools::reliabilityL2(fit_Rutter_bif, General_2nd)
##Graph
semPaths(fit_Rutter_bif, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2) # Technical representation

# Model comparison
lavTestLRT(fit_Rutter_1F, fit_Rutter_2F, fit_Rutter_bif)

# MG-CFA - Invariance testing

## Function
minvariance <- function(basal, group, model_name){
  library(tidyverse)
  
  # fitting models
  config <- update(basal, group = group)
  loadings  <- update(basal, group = group, group.equal = c("loadings"))
  thresholds <- update(basal, group = group, group.equal = c("loadings", "thresholds"))
  residuals <- update(basal, group = group, group.equal = c("loadings","thresholds", "residuals"))
  
  # anova
  anova <- lavTestLRT(config, loadings, thresholds, residuals) %>% as_tibble(rownames = "id") 
  # estimates
  est <- lst(config, loadings, thresholds, residuals) %>% 
    map_dfr(~fitmeasures(., fit.measures = c("chisq","df","pvalue","rmsea.scaled", "cfi.scaled", "tli.scaled", "srmr")), .id = "id") %>% 
    left_join(anova) %>%
    transmute(model = model_name,
              id,
              across(c(chisq:srmr), as.numeric),
              df, 
              ddf = `Df diff`,
              chisq_diff = `Chisq diff`,
              p_anova = `Pr(>Chisq)`,
              dcfi = abs(cfi.scaled - lag(cfi.scaled)),
              dcfi_s = if_else(dcfi >= 0.01, "*", NA_character_),
              drmsea = abs(rmsea.scaled - lag(rmsea.scaled)),
              drmsea_s = if_else(drmsea >= 0.015, "*", NA_character_),
              dsrmr = abs(srmr - lag(srmr)),
              dsrmr_s = if_else(dsrmr >= 0.015, "*", NA_character_),
              ) %>% 
    relocate(model, .before=1)
  
  return(est)
}

# Estimating model
Rutter_model_2F_Informant <- '
Internalizing_Corr =~ Miserable +  Worries +  Solitary 
Externalizing_Corr =~ Disobedient +  Fights +  Destroys +  Fidgety +  Unsettle +  Irritable
'
fit_Rutter_2F_Informant <- cfa(Rutter_model_2F_Informant, data=mydata_Rutter_16_MI, ordered = T, std.lv = T, estimator="WLSMV"); summary(fit_Rutter_2F_Informant,fit.measures=T, standardized=T, rsquare=T)
# Modification indices
Mod_Indices_Rutter_2F_Informant <- modindices(fit_Rutter_2F_Informant, sort = TRUE, maximum.number = 10); Mod_Indices_Rutter_2F_Informant[Mod_Indices_Rutter_2F_Informant$op == "~~",]
#Reliability
semTools::reliability(fit_Rutter_2F_Informant)
##Graph
semPaths(fit_Rutter_2F_Informant, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5), edge.color = "black", reorder = F, edge.label.cex=1.2,) # Technical representation

## Estimating invariance
MI_fit_Rutter_2F_Informant <- minvariance(fit_Rutter_2F_Informant, group = "Informant", model_name = "Rutter informant invariance"); MI_fit_Rutter_2F_Informant

# Distribuition plots and informant mean differences

## add data
pred_Rutter_invariance<- fit_Rutter_2F_Informant %>% lavPredict()
mydata_Rutter_16_MI <- cbind(mydata_Rutter_16_MI,pred_Rutter_invariance)

## Test mean differences for internalizing
Int.aov <- aov(Internalizing_Corr ~ Informant, data = mydata_Rutter_16_MI); summary(Int.aov); TukeyHSD(Int.aov)
t.test(Internalizing_Corr ~ Informant, data = mydata_Rutter_16_MI)
pairwise_t_test_Internalizing <- rstatix::pairwise_t_test(Internalizing_Corr ~ Informant, data = mydata_Rutter_16_MI, p.adjust.method = "BH", ref.group="Parent")
### Plots
Internalizing_by_Informant_box <- position_Internalizing_inf <- pairwise_t_test_Internalizing %>% add_xy_position(x = "Informant")
ggboxplot(mydata_Rutter_16_MI, x = "Informant", y = "Internalizing_Corr", fill="Informant") +
  stat_pvalue_manual(position_Internalizing_inf, hide.ns = TRUE, tip.length = 0.01, y.position = c(2), bracket.shorten = 0.05) +
  labs(subtitle = get_test_label(pairwise_t_test_Internalizing, detailed = TRUE),caption = get_pwc_label(position_Internalizing_inf)) +
  xlab("Informant")+ylab("Internalizing factor score") + 
  geom_jitter(shape=16, position=position_jitter(0.2),alpha=1/4, size=1) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) + 
  theme(legend.position="none"); Internalizing_by_Informant_box

hist_Rutter_Internalizing_invariance<-ggplot(mydata_Rutter_16_MI, aes(Internalizing_Corr, colour=Informant)) + geom_density(show.legend = T) + xlab("Internalizing factor scores by Informant")+ylim(0,1)+xlim(-3,3); hist_Rutter_Internalizing_invariance

Internalizing_by_Informant <- mydata_Rutter_16_MI %>%
  ggplot( aes(x=Internalizing_Corr, fill=Informant)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    xlab("Informant")+ylab("Internalizing factor score") + 
  labs(title = 'Internalizing score by Informant') +
    theme_ipsum() +
    labs(fill=""); Internalizing_by_Informant

## Test mean differences for internalizing
Ext.aov <- aov(Externalizing_Corr ~ Informant, data = mydata_Rutter_16_MI); summary(Ext.aov); TukeyHSD(Ext.aov)
t.test(Externalizing_Corr ~ Informant, data = mydata_Rutter_16_MI)
pairwise_t_test_Externalizing <- rstatix::pairwise_t_test(Externalizing_Corr ~ Informant, data = mydata_Rutter_16_MI, p.adjust.method = "BH", ref.group="Parent")
### Plots
position_Externalizing_inf <- pairwise_t_test_Externalizing %>% add_xy_position(x = "Informant")
Externalizing_by_Informant_box <- ggboxplot(mydata_Rutter_16_MI, x = "Informant", y = "Externalizing_Corr", fill="Informant") +
  stat_pvalue_manual(position_Externalizing_inf, hide.ns = TRUE, tip.length = 0.01, y.position = c(2), bracket.shorten = 0.05) +
  labs(subtitle = get_test_label(pairwise_t_test_Externalizing, detailed = TRUE),caption = get_pwc_label(position_Externalizing_inf)) +
  xlab("Informant")+ylab("Externalizing factor score") + 
  geom_jitter(shape=16, position=position_jitter(0.2),alpha=1/4, size=1) + 
  scale_fill_manual(values=c("#69b3a2", "#404080")) + 
  theme(legend.position="none"); Externalizing_by_Informant_box

hist_Rutter_Externalizing_invariance<-ggplot(mydata_Rutter_16_MI, aes(Externalizing_Corr, colour=Informant)) + geom_density(show.legend = T) + xlab("Externalizing factor scores by Informant")+ylim(0,1)+xlim(-3,3); hist_Rutter_Externalizing_invariance

Externalizing_by_Informant <- mydata_Rutter_16_MI %>%
  ggplot( aes(x=Externalizing_Corr, fill=Informant)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'identity') +
    scale_fill_manual(values=c("#69b3a2", "#404080")) +
    xlab("Informant")+ylab("Externalizing factor score") + 
  labs(title = 'Externalizing score by Informant') +
    theme_ipsum() +
    labs(fill=""); Externalizing_by_Informant


gridExtra::grid.arrange(hist_Rutter_Internalizing_invariance, Internalizing_by_Informant, hist_Rutter_Externalizing_invariance, Externalizing_by_Informant,ncol=2,nrow=2)

```
## IRT
```{r IRT for the Rutter Scale, message=F, warning=F}
#######
# IRT #
#######
library(ltm); library(mirt)

mydata_Rutter_16T_Total <- mydata_Rutter_16_fa %>% dplyr::select(B_Disobedient, B_Fights, B_Destroys, B_Fidgety, B_Unsettle, B_Irritable, B_Miserable, B_Worries, B_Solitary)
mydata_Rutter_16T_Total<-na.omit(mydata_Rutter_16T_Total)
# Total scores
items_Rutter_16T <- list(Rutter_Total=c("B_Disobedient", "B_Fights", "B_Destroys", "B_Fidgety", "B_Unsettle", "B_Irritable", "B_Miserable", "B_Worries", "B_Solitary"),
                       Rutter_Int=c("B_Miserable", "B_Worries", "B_Solitary"), 
                       Rutter_Ext=c("B_Disobedient", "B_Fights", "B_Destroys", "B_Fidgety", "B_Unsettle", "B_Irritable")) 
score_Rutter_16T <- scoreItems(items_Rutter_16T,mydata_Rutter_16T_Total,totals = T) 
#score_Rutter$scores[score_Rutter$missing > 0] <- NA
mydata_Rutter_16T_Total$Rutter_Total<-as.numeric(score_Rutter_16T$scores[,1])
mydata_Rutter_16T_Total$Rutter_Int_total<-as.numeric(score_Rutter_16T$scores[,2])
mydata_Rutter_16T_Total$Rutter_Ext_total<-as.numeric(score_Rutter_16T$scores[,3])
hist(mydata_Rutter_16T_Total$Rutter_Total)
hist(mydata_Rutter_16T_Total$Rutter_Int_total)
hist(mydata_Rutter_16T_Total$Rutter_Ext_total)

# IRT
## data
mydata_Rutter_16T_IRT <- mydata_Rutter_16_fa %>% dplyr::select(B_Disobedient, B_Fights, B_Destroys, B_Fidgety, B_Unsettle, B_Irritable, B_Miserable, B_Worries, B_Solitary) %>% mutate_all(~as.character(.) %>% as.numeric())
mydata_Rutter_16T_IRT<-na.omit(mydata_Rutter_16T_IRT)

## Graded Response Model - unidimensional
Rutter_1F_grm <- grm(mydata_Rutter_16T_IRT); Rutter_1F_grm
plot(Rutter_1F_grm, type = "IIC", items = 0, main="Rutter general information curve", ylab = "Information", xlab = "Rutter behavioural and emotional latent trait")

# Characteristic of the instrument
par(mfrow = c(3, 3))
plot(Rutter_1F_grm,type="ICC")
par(mfrow = c(1, 1))
# Information  of the instrument
plot(Rutter_1F_grm,type="IIC", main="Rutter item information curve", ylab = "Information", xlab = "Rutter behavioural and emotional latent trait")
#Psych IRT (Reliability by area of the latent trait)
irt.fa(mydata_Rutter_16T_IRT)

#Loadings
summary(Rutter_1F_grm)
# coefficients
coef(Rutter_1F_grm)

#IRT score
Rutter_1F_grm_fs<-factor.scores.grm(Rutter_1F_grm, resp.patterns = mydata_Rutter_16T_IRT)
Rutter_1F_grm_fs<-Rutter_1F_grm_fs$score.dat$z1
Rutter_1F_grm_fs<-as.data.frame(Rutter_1F_grm_fs)
mydata_Rutter_16T_IRT$Rutter_1F_fs<-Rutter_1F_grm_fs[,1]
hist(mydata_Rutter_16T_IRT$Rutter_1F_fs)
summary(mydata_Rutter_16T_IRT$Rutter_1F_fs)

# combine total and IRT-based factor score
mydata_Rutter_16T_uni <- cbind(mydata_Rutter_16T_Total, mydata_Rutter_16T_IRT) %>% dplyr::select(Rutter_Total:Rutter_Ext_total, Rutter_1F_fs)
# Correlation between total and factor scores
plot(mydata_Rutter_16T_uni$Rutter_Total,mydata_Rutter_16T_uni$Rutter_1F_fs, main="Correlation between Rutter total and IRT-based factor score", ylab = "Rutter factor score", xlab = "Rutter total score")
ggscatter(mydata_Rutter_16T_uni, x = "Rutter_Total", y = "Rutter_1F_fs", 
          add = "reg.line", conf.int = T, 
          cor.coef = T, cor.method = "pearson",
          xlab = "Rutter total score", ylab = "Rutter factor score", 
          main="Correlation between Rutter total and IRT-based factor score")

#################################
# MIRT - Multidimensional model #

mydata_Rutter_16T_MIRT <- mydata_Rutter_16T_IRT %>% dplyr::select(B_Disobedient:B_Solitary)

Rutter_16T_mirt <- mirt.model('Externalizing_fs = 1-6
                              Internalizing_fs = 7-9')

# MIRT model
fit_Rutter_16T_mirt <- mirt(mydata_Rutter_16T_MIRT, model = Rutter_16T_mirt, itemtype="graded", verbose=FALSE); fit_Rutter_16T_mirt

# Information  of the instrument
plot(fit_Rutter_16T_mirt, type="info")
# Characteristic of the instrument
plot(fit_Rutter_16T_mirt, type="trace")
#Loadings
summary(fit_Rutter_16T_mirt)
#Coefficients
coef(fit_Rutter_16T_mirt)
mod2values(fit_Rutter_16T_mirt)

# MIRT score
mydata_Rutter_16T_MIRT_fscores<-fscores(fit_Rutter_16T_mirt)
mydata_Rutter_16T_MIRT_fscores<-as.data.frame(mydata_Rutter_16T_MIRT_fscores)
mydata_Rutter_16T_mult <- cbind(mydata_Rutter_16T_Total, mydata_Rutter_16T_MIRT)
mydata_Rutter_16T_mult <- cbind(mydata_Rutter_16T_mult, mydata_Rutter_16T_MIRT_fscores)
mydata_Rutter_16T_mult <- mydata_Rutter_16T_mult %>% dplyr::select(B_Disobedient:Rutter_Ext_total, Externalizing_fs:Internalizing_fs)
hist(mydata_Rutter_16T_mult$Externalizing_fs)
hist(mydata_Rutter_16T_mult$Internalizing_fs)

# Correlation between total and factor scores
ggscatter(mydata_Rutter_16T_mult, x = "Rutter_Ext_total", y = "Externalizing_fs", 
          add = "reg.line", conf.int = T, 
          cor.coef = T, cor.method = "pearson",
          xlab = "Rutter total externalizing score", ylab = "Rutter externalizing factor score", 
          main="Correlation between Rutter total and IRT-based externalizing scores")

ggscatter(mydata_Rutter_16T_mult, x = "Rutter_Int_total", y = "Internalizing_fs", 
          add = "reg.line", conf.int = T, 
          cor.coef = T, cor.method = "pearson",
          xlab = "Rutter total Internalizing score", ylab = "Rutter Internalizing factor score", 
          main="Correlation between Rutter total and IRT-based Internalizing scores")

```

# SEM
```{r SEM, message=F, warning=F}
# Data
mydata_sem <- mydata %>% dplyr::select(ncdsid:n0rgsc, n7rgsc, n11rgsc, n16rgsc, n7read, n11read, n16read, n7math,  n11maths, n16math, zn7read, zn11read, zn16read, zn7math, zn11math, zn16math, A_Disobedient_7, A_Fights_7, A_Destroys_7, A_Fidgety_7, A_Unsettle_7, A_Irritable_7, A_Miserable_7, A_Worries_7, A_Solitary_7, A_Disobedient_11, A_Fights_11, A_Destroys_11, A_Fidgety_11, A_Unsettle_11, A_Irritable_11, A_Miserable_11, A_Worries_11, A_Solitary_11, A_Disobedient_16, A_Fights_16, A_Destroys_16, A_Fidgety_16, A_Unsettle_16, A_Irritable_16, A_Miserable_16, A_Worries_16, A_Solitary_16, A_Rutter_total_7, A_Rutter_total_11, A_Rutter_total_16, ipw_read16)

mydata_sem$n0bwght_kg <- mydata_sem$n0bwght/1000

#mydata_sem <- mydata_sem %>% mutate_at(vars(starts_with("A_")),ordered) 
#mydata_sem <- mydata_sem %>% mutate_at(vars(contains("n0sex")),ordered) 
#mydata_sem <- mydata_sem %>% mutate_at(vars(contains("n0region")),factor) 
#mydata_sem <- mydata_sem %>% mutate_at(vars(contains("rgsc")),ordered) 

options(max.print=1000000)

# generating Externaliizng total score to LGM
items_Rutter_Ext <- list(Rutter_Ext_7=c("A_Disobedient_7", "A_Fights_7", "A_Destroys_7", "A_Fidgety_7", "A_Unsettle_7", "A_Irritable_7"), 
                   Rutter_Ext_11=c("A_Disobedient_11", "A_Fights_11", "A_Destroys_11", "A_Fidgety_11", "A_Unsettle_11", "A_Irritable_11"),
                   Rutter_Ext_16=c("A_Disobedient_16", "A_Fights_16", "A_Destroys_16", "A_Fidgety_16", "A_Unsettle_16", "A_Irritable_16")) 

score_Rutter_Ext <- scoreItems(items_Rutter_Ext,mydata_sem,totals = T) 
#score_Rutter$scores[score_Rutter$missing > 0] <- NA
mydata_sem$A_Rutter_Total_Ext_7<-as.numeric(score_Rutter_Ext$scores[,1])
mydata_sem$A_Rutter_Total_Ext_11<-as.numeric(score_Rutter_Ext$scores[,2])
mydata_sem$A_Rutter_Total_Ext_16<-as.numeric(score_Rutter_Ext$scores[,3])
hist(mydata_sem$A_Rutter_Total_Ext_7)
hist(mydata_sem$A_Rutter_Total_Ext_11)
hist(mydata_sem$A_Rutter_Total_Ext_16)

# POMS score
mydata_sem$A_Rutter_POMS_Ext_7 <- ((mydata_sem$A_Rutter_Total_Ext_7-0)/(12-0))*100
mydata_sem$A_Rutter_POMS_Ext_11 <- ((mydata_sem$A_Rutter_Total_Ext_11-0)/(12-0))*100
mydata_sem$A_Rutter_POMS_Ext_16 <- ((mydata_sem$A_Rutter_Total_Ext_16-0)/(12-0))*100

# z-score
mydata_sem$A_Rutter_Total_Ext_7_z <- scale(mydata_sem$A_Rutter_Total_Ext_7, center = TRUE, scale = TRUE); mydata_sem$A_Rutter_Total_Ext_7_z <- as.numeric(mydata_sem$A_Rutter_Total_Ext_7_z); summary(mydata_sem$A_Rutter_Total_Ext_7_z); hist(mydata_sem$A_Rutter_Total_Ext_7_z)

mydata_sem$A_Rutter_Total_Ext_11_z <- scale(mydata_sem$A_Rutter_Total_Ext_11, center = TRUE, scale = TRUE); mydata_sem$A_Rutter_Total_Ext_11_z <- as.numeric(mydata_sem$A_Rutter_Total_Ext_11_z); summary(mydata_sem$A_Rutter_Total_Ext_11_z); hist(mydata_sem$A_Rutter_Total_Ext_11_z)

mydata_sem$A_Rutter_Total_Ext_16_z <- scale(mydata_sem$A_Rutter_Total_Ext_16, center = TRUE, scale = TRUE); mydata_sem$A_Rutter_Total_Ext_16_z <- as.numeric(mydata_sem$A_Rutter_Total_Ext_16_z); summary(mydata_sem$A_Rutter_Total_Ext_16_z); hist(mydata_sem$A_Rutter_Total_Ext_16_z)

# Recoding and filtering data
#get_labels(mydata_sem$n0sex)
#mydata_sem <- mydata_sem %>% mutate(n0sex = car::recode(n0sex, "1=0; 2=1"))
#get_labels(mydata_sem$n0rgsc)
#mydata_sem <- mydata_sem %>% mutate(n0rgsc = car::recode(n0rgsc, "1=0; 2=1; 3=2; 4=3; 5=4; 6=5"))


mydata_sem <- mydata_sem %>% mutate(ipw_read16 = car::recode(ipw_read16, "NA=99"))
mydata_sem <- mydata_sem %>% dplyr::filter(ipw_read16!=99)
#############################################################
# Cross-lagged for internalizing and externalizing symptoms #

# Traditional CLPM
clpm_ext_read <- '
# Random intercepts - set to zero for becoming a CLPM
RI_ext =~ 1*A_Rutter_Total_Ext_7 + 1*A_Rutter_Total_Ext_11 + 1*A_Rutter_Total_Ext_16
RI_read =~ 1*n7read + 1*n11read + 1*n16read

# Set variance and covariance of random intercepts to be zero -> this makes RI-CLPM to be nusual CLPM
RI_ext ~~ 0*RI_ext
RI_read ~~ 0*RI_read
RI_ext ~~ 0*RI_read

# Observed var intercepts (triangles on schematic plots)
A_Rutter_Total_Ext_7 ~ iext1*1 
A_Rutter_Total_Ext_11 ~ iext2*1
A_Rutter_Total_Ext_16 ~ iext3*1
n7read ~ iread1*1
n11read ~ iread2*1
n16read ~ iread3*1

# Create within-person centered latent variables
l_ext_a7 =~ 1*A_Rutter_Total_Ext_7
l_ext_a11 =~ 1*A_Rutter_Total_Ext_11
l_ext_a16 =~ 1*A_Rutter_Total_Ext_16
l_read_a7 =~ 1*n7read 
l_read_a11 =~ 1*n11read 
l_read_a16 =~ 1*n16read 

# Estimate lagged effects between within-person centered variables
## Autoregressive paths
l_read_a11 ~ l_read_a7
l_read_a16 ~ l_read_a11
l_ext_a11 ~ l_ext_a7 
l_ext_a16 ~ l_ext_a11
## Cross-lagged paths
l_read_a11 ~ l_ext_a7 
l_read_a16 ~ l_ext_a11 
l_ext_a11 ~ l_read_a7
l_ext_a16 ~ l_read_a11

# Estimate (residual) variance of within-person centered exogenous variables
l_ext_a7 ~~ l_ext_a7 
l_ext_a11 ~~ l_ext_a11
l_ext_a16 ~~ l_ext_a16 
l_read_a7 ~~ l_read_a7 
l_read_a11 ~~ l_read_a11
l_read_a16 ~~ l_read_a16 

# Estimate covariance between within-person centered exogenous variables
l_ext_a7 ~~ l_read_a7
l_ext_a11 ~~ l_read_a11
l_ext_a16 ~~ l_read_a16 
'


sem_clpm_ext_read <- lavaan(clpm_ext_read, data=mydata_sem, std.lv = F, # sets latent vars or its residuals to unity
                                 missing="ML", sampling.weights = "ipw_read16",
                                 int.ov.free = F, int.lv.free = F, auto.fix.first = F, auto.fix.single = F, 
                                 auto.cov.lv.x = F, auto.cov.y = F, auto.var = F)

summary(sem_clpm_ext_read, fit.measures=T, standardized=T, rsquare=T)
parameterEstimates(sem_clpm_ext_read, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op == "~") %>% 
  dplyr::select('Regressions'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Regression coeficients from CLPM")

Paths_sem_clpm_ext_read <- parameterEstimates(sem_clpm_ext_read, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op != "=~") %>% 
  dplyr::select('Regression and correlations'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) 
Paths_sem_clpm_ext_read <- Paths_sem_clpm_ext_read[10:26,]
#xlsx::write.xlsx(Paths_sem_clpm_ext_read, file = "Ext_Read_Results_NCDS.xlsx", sheetName="clpm_ext_read", append = T)

semPaths(sem_clpm_ext_read, "std", layout = "tree3", edge.label.cex = 1.0,sizeMan2 = 8.0, sizeMan = 8.0,rotation=3, residuals=F, intercepts = F,  posCol=c("skyblue3"))
semPaths(sem_clpm_ext_read, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5,6,7), edge.color = "black", reorder = F) 

# RI-CLPM
riclpm_ext_read <- '
# Random intercepts 
RI_ext =~ 1*A_Rutter_Total_Ext_7 + 1*A_Rutter_Total_Ext_11 + 1*A_Rutter_Total_Ext_16
RI_read =~ 1*n7read + 1*n11read + 1*n16read

# Set variance and covariance of random intercepts
RI_ext ~~ RI_ext
RI_read ~~ RI_read
RI_ext ~~ RI_read

# Observed var intercepts (triangles on schematic plots)
A_Rutter_Total_Ext_7 ~ iext1*1 
A_Rutter_Total_Ext_11 ~ iext2*1
A_Rutter_Total_Ext_16 ~ iext3*1
n7read ~ iread1*1
n11read ~ iread2*1
n16read ~ iread3*1

# Create within-person centered latent variables
l_ext_a7 =~ 1*A_Rutter_Total_Ext_7
l_ext_a11 =~ 1*A_Rutter_Total_Ext_11
l_ext_a16 =~ 1*A_Rutter_Total_Ext_16
l_read_a7 =~ 1*n7read 
l_read_a11 =~ 1*n11read 
l_read_a16 =~ 1*n16read 

# Estimate lagged effects between within-person centered variables
## Autoregressive paths
l_read_a11 ~ l_read_a7
l_read_a16 ~ l_read_a11
l_ext_a11 ~ l_ext_a7 
l_ext_a16 ~ l_ext_a11
## Cross-lagged paths
l_read_a11 ~ l_ext_a7 
l_read_a16 ~ l_ext_a11 
l_ext_a11 ~ l_read_a7
l_ext_a16 ~ l_read_a11

# Estimate (residual) variance of within-person centered exogenous variables
l_ext_a7 ~~ l_ext_a7 
l_ext_a11 ~~ l_ext_a11
l_ext_a16 ~~ l_ext_a16 
l_read_a7 ~~ l_read_a7 
l_read_a11 ~~ l_read_a11
l_read_a16 ~~ l_read_a16 

# Estimate covariance between within-person centered exogenous variables
l_ext_a7 ~~ l_read_a7
l_ext_a11 ~~ l_read_a11
l_ext_a16 ~~ l_read_a16 
'


sem_riclpm_ext_read <- lavaan(riclpm_ext_read, data=mydata_sem, std.lv = F, # sets latent vars or its residuals to unity
                                 missing="ML", sampling.weights = "ipw_read16", 
                                 int.ov.free = F, int.lv.free = F, auto.fix.first = F, auto.fix.single = F, 
                                 auto.cov.lv.x = F, auto.cov.y = F, auto.var = F)

summary(sem_riclpm_ext_read, fit.measures=T, standardized=T, rsquare=T)
parameterEstimates(sem_riclpm_ext_read, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op == "~") %>% 
  dplyr::select('Regressions'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Regression coeficients from riclpm")

Paths_sem_riclpm_ext_read <- parameterEstimates(sem_riclpm_ext_read, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op != "=~") %>% 
  dplyr::select('Regression and correlations'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) 
Paths_sem_riclpm_ext_read <- Paths_sem_riclpm_ext_read[10:26,]
#xlsx::write.xlsx(Paths_sem_riclpm_ext_read, file = "Ext_Read_Results_NCDS.xlsx", sheetName="riclpm_ext_read", append = T)

semPaths(sem_riclpm_ext_read, "std", layout = "tree3", edge.label.cex = 1.0,sizeMan2 = 8.0, sizeMan = 8.0,rotation=3, residuals=F, intercepts = F,  posCol=c("skyblue3"))

semPaths(sem_riclpm_ext_read, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5,6,7), edge.color = "black", reorder = F) 

# Adjusted RI-CLPM
riclpm_ext_read_adj <- '
# Random intercepts 
RI_ext =~ 1*A_Rutter_Total_Ext_7 + 1*A_Rutter_Total_Ext_11 + 1*A_Rutter_Total_Ext_16
RI_read =~ 1*n7read + 1*n11read + 1*n16read

# Set variance and covariance of random intercepts
RI_ext ~~ RI_ext
RI_read ~~ RI_read
RI_ext ~~ RI_read

# Observed var intercepts (triangles on schematic plots)
A_Rutter_Total_Ext_7 ~ iext1*1 
A_Rutter_Total_Ext_11 ~ iext2*1
A_Rutter_Total_Ext_16 ~ iext3*1
n7read ~ iread1*1
n11read ~ iread2*1
n16read ~ iread3*1

# Create within-person centered latent variables
l_ext_a7 =~ 1*A_Rutter_Total_Ext_7
l_ext_a11 =~ 1*A_Rutter_Total_Ext_11
l_ext_a16 =~ 1*A_Rutter_Total_Ext_16
l_read_a7 =~ 1*n7read 
l_read_a11 =~ 1*n11read 
l_read_a16 =~ 1*n16read 

# Estimate lagged effects between within-person centered variables
## Autoregressive paths
l_read_a11 ~ l_read_a7
l_read_a16 ~ l_read_a11
l_ext_a11 ~ l_ext_a7 
l_ext_a16 ~ l_ext_a11
## Cross-lagged paths
l_read_a11 ~ l_ext_a7 
l_read_a16 ~ l_ext_a11 
l_ext_a11 ~ l_read_a7
l_ext_a16 ~ l_read_a11

# Estimate (residual) variance of within-person centered exogenous variables
l_ext_a7 ~~ l_ext_a7 
l_ext_a11 ~~ l_ext_a11
l_ext_a16 ~~ l_ext_a16 
l_read_a7 ~~ l_read_a7 
l_read_a11 ~~ l_read_a11
l_read_a16 ~~ l_read_a16 

# Estimate covariance between within-person centered exogenous variables
l_ext_a7 ~~ l_read_a7
l_ext_a11 ~~ l_read_a11
l_ext_a16 ~~ l_read_a16 

# Adjusted
RI_ext ~ n0bwght_kg + n0rgsc
RI_read ~ n0bwght_kg + n0rgsc

# Variance and Covariance of covariates
n0bwght_kg ~~ n0bwght_kg
n0rgsc ~~ n0rgsc

# covar intercept
n0bwght_kg ~ ibw*1
n0rgsc ~ irgsc*1

n0bwght_kg ~~ n0rgsc
'


sem_riclpm_ext_read_adj <- lavaan(riclpm_ext_read_adj, data=mydata_sem, std.lv = F, # sets latent vars or its residuals to unity
                                 missing="ML", sampling.weights = "ipw_read16", 
                                 int.ov.free = F, int.lv.free = F, auto.fix.first = F, auto.fix.single = F, 
                                 auto.cov.lv.x = F, auto.cov.y = F, auto.var = F)

summary(sem_riclpm_ext_read_adj, fit.measures=T, standardized=T, rsquare=T)
parameterEstimates(sem_riclpm_ext_read_adj, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op == "~") %>% 
  dplyr::select('Regressions'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Regression coeficients from riclpm")

Paths_sem_riclpm_ext_read_adj <- parameterEstimates(sem_riclpm_ext_read_adj, ci = TRUE, level = 0.95, boot.ci.type = "perc", standardized = TRUE) %>% 
  filter(op != "=~") %>% 
  dplyr::select('Regression and correlations'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) 
Paths_sem_riclpm_ext_read_adj <- Paths_sem_riclpm_ext_read_adj[10:26,]
#xlsx::write.xlsx(Paths_sem_riclpm_ext_read_adj, file = "Ext_Read_Results_NCDS.xlsx", sheetName="riclpm_ext_read_adj", append = T)

semPaths(sem_riclpm_ext_read_adj, "std", layout = "tree3", edge.label.cex = 1.0,sizeMan2 = 8.0, sizeMan = 8.0,rotation=3, residuals=F, intercepts = F,  posCol=c("skyblue3"))

semPaths(sem_riclpm_ext_read_adj, "mod", "est", ask=FALSE, layout = "tree3",
         levels = c(1,2,3,4,5,6,7), edge.color = "black", reorder = F) 

# Compare fit from CLPM and RI-CLPM
lavTestLRT(sem_riclpm_ext_read, sem_clpm_ext_read)
lavTestLRT(sem_riclpm_ext_read, sem_riclpm_ext_read_adj)

#######################
# Latent Growth model #
Rutter_LGM_Rutter_total <- '

# Growth variables
Intercep =~ 1*A_Rutter_Total_Ext_7 + 1*A_Rutter_Total_Ext_11 + 1*A_Rutter_Total_Ext_16
Slope =~  0*A_Rutter_Total_Ext_7 + 4*A_Rutter_Total_Ext_11 + 9*A_Rutter_Total_Ext_16

# Time-varying covariates
#A_Rutter_Total_Ext_7 ~ n7rgsc
#A_Rutter_Total_Ext_11 ~ n11rgsc
#A_Rutter_Total_Ext_16 ~ n16rgsc

# Regressions
Intercep ~ n0sex + n0bwght_kg + n0rgsc
Slope ~ n0sex + n0bwght_kg + n0rgsc

# Fix residual variance as in mixed model
A_Rutter_Total_Ext_7 ~~a*A_Rutter_Total_Ext_7
A_Rutter_Total_Ext_11 ~~a*A_Rutter_Total_Ext_11
A_Rutter_Total_Ext_16 ~~a*A_Rutter_Total_Ext_16
'

# Fitting the model
fit_Rutter_LGM_Rutter_total <- lavaan::growth(Rutter_LGM_Rutter_total, data=mydata_sem, ordered = F, std.lv=T, estimator="MLR", missing="fiml",  sampling.weights = "ipw_read16", ); summary(fit_Rutter_LGM_Rutter_total,fit.measures=F, standardized=F, rsquare=F)

##Graph
semPaths(fit_Rutter_LGM_Rutter_total, "mod", "est", ask=FALSE, layout = "tree3",rotation=2,
         levels = c(1,2,3,4,5,6,7), edge.color = "black", reorder = F, edge.label.cex=1.2,) # Technical representation
semPaths(fit_Rutter_LGM_Rutter_total,"diagram", "est", layout = "tree3", edge.label.cex = 1.0,sizeMan2 = 8.0, sizeMan = 8.0, rotation=2, residuals=F, intercepts = F)


# Trajectory
## Data
mydata_sem_ext_trajectory_7 <- mydata_sem %>% dplyr::select(ncdsid, n0sex, A_Rutter_Total_Ext_7) %>% rename(A_Rutter_Total_Ext = A_Rutter_Total_Ext_7); mydata_sem_ext_trajectory_7$Wave <- "Age_7"
mydata_sem_ext_trajectory_11 <- mydata_sem %>% dplyr::select(ncdsid, n0sex, A_Rutter_Total_Ext_11) %>% rename(A_Rutter_Total_Ext = A_Rutter_Total_Ext_11); mydata_sem_ext_trajectory_11$Wave <- "Age_11"
mydata_sem_ext_trajectory_16 <- mydata_sem %>% dplyr::select(ncdsid, n0sex, A_Rutter_Total_Ext_16) %>% rename(A_Rutter_Total_Ext = A_Rutter_Total_Ext_16); mydata_sem_ext_trajectory_16$Wave <- "Age_16"
mydata_sem_ext_trajectory <- rbind(mydata_sem_ext_trajectory_7, mydata_sem_ext_trajectory_11, mydata_sem_ext_trajectory_16)
mydata_sem_ext_trajectory$Wave <- fct_relevel(mydata_sem_ext_trajectory$Wave, "Age_7", "Age_11", "Age_16")
mydata_sem_ext_trajectory <- mydata_sem_ext_trajectory %>% drop_na()

## Plot
plot_ext_trajectory <- ggplot(mydata_sem_ext_trajectory, aes(y=A_Rutter_Total_Ext, x=as.factor(Wave), fill=as.factor(n0sex))) + geom_boxplot() + 
  xlab("Wave")+ylab("Externalizing score"); plot_ext_trajectory

## Checking sex differences with series of t-tests
t.test(A_Rutter_Total_Ext_7 ~ n0sex, data = mydata_sem)
t.test(A_Rutter_Total_Ext_11 ~ n0sex, data = mydata_sem)
t.test(A_Rutter_Total_Ext_16 ~ n0sex, data = mydata_sem)

```

